-- docs/database/schema.sql
-- ============================================================
-- SCHEMA: Cafetería SAS — Dashboard de Pronóstico de Demanda
-- ============================================================
-- Descripción:  Definición completa del esquema de base de datos en Supabase
-- Versión:      1.0
-- Última actualización: 2026-03-22
-- Plataforma:   Supabase (PostgreSQL 15+)
-- Base de datos: cafeteria_sas

-- ⚠️  MANDATO DE MANTENIMIENTO:
-- Después de ejecutar CREATE TABLE en Supabase, actualizar este archivo
-- inmediatamente. Referencia: CLAUDE.md §5 (Estándares de Código).

-- ============================================================
-- 1. FUNCIONES AUXILIARES
-- ============================================================

create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- ============================================================
-- 2. TABLAS DE DATOS
-- ============================================================

-- TABLE: usr_ventas
-- DESCRIPCIÓN: Registro diario de unidades vendidas, pagadas y bonificadas.
--              Fuente de verdad para la demanda histórica. Grano: 1 registro/día.
-- PROPÓSITO:   Input principal para el modelo de pronóstico.
-- GRANULARIDAD: Diaria (fecha con timestamp)
-- ACTUALIZACIÓN: Diaria, al cierre de operaciones (antes de 6:00 PM según CLAUDE.md §8)
create table public.usr_ventas (
  id bigint generated by default as identity not null,
  fecha timestamp with time zone not null,
  unidades_vendidas integer not null,
  unidades_pagadas integer not null,
  unidades_bonificadas integer not null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  pyme_id text not null default '001_ABC'::text,
  constraint usr_ventas_pkey primary key (id)
) tablespace pg_default;

create trigger update_usr_ventas_updated_at before update on usr_ventas
for each row execute function update_updated_at_column();

-- TABLE: usr_produccion
-- DESCRIPCIÓN: Estimación de producción vs. venta real y cálculo de merma.
--              Permite evaluar eficiencia de producción y residuos.
-- PROPÓSITO:   Minimización de desperdicio (CLAUDE.md §2).
-- GRANULARIDAD: Diaria (fecha sin timestamp)
-- ACTUALIZACIÓN: Diaria, a demanda (después de ventas confirmadas)
create table public.usr_produccion (
  id bigint generated by default as identity not null,
  fecha date not null,
  unidades_vendidas integer not null,
  produccion_estimada integer not null,
  unidades_sobrantes integer not null,
  porcentaje_merma numeric(5, 2) null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  pyme_id text not null default '001_ABC'::text,
  constraint usr_produccion_pkey primary key (id)
) tablespace pg_default;

create trigger update_usr_produccion_updated_at before update on usr_produccion
for each row execute function update_updated_at_column();

-- TABLE: usr_clima
-- DESCRIPCIÓN: Condiciones climáticas diarias.
-- PROPÓSITO:   Variable exógena candidata para el modelo (CLAUDE.md §7: protocolo de variables exógenas).
--              Incluir solo si MAPE mejora en validación cruzada.
-- GRANULARIDAD: Diaria (fecha con timestamp, aunque podría ser date)
-- ACTUALIZACIÓN: Diaria, desde API externa o ingesta manual
create table public.usr_clima (
  id bigint generated by default as identity not null,
  fecha timestamp with time zone not null,
  estado_clima text not null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  pyme_id text not null default '001_ABC'::text,
  constraint usr_clima_pkey primary key (id)
) tablespace pg_default;

create trigger update_usr_clima_updated_at before update on usr_clima
for each row execute function update_updated_at_column();

-- TABLE: usr_macro_anual
-- DESCRIPCIÓN: Indicadores macroeconómicos anuales (SMMLV = Salario Mínimo Mensual Legal Vigente).
-- PROPÓSITO:   Variable exógena para correlacionar poder adquisitivo con demanda (CLAUDE.md §8).
-- GRANULARIDAD: Anual (fecha como date)
-- ACTUALIZACIÓN: Anual (principios de año) o a demanda
create table public.usr_macro_anual (
  id bigint generated by default as identity not null,
  fecha date not null,
  smmlv numeric(12, 2) null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  pyme_id text not null default '001_ABC'::text,
  constraint usr_macro_anual_pkey primary key (id)
) tablespace pg_default;

create trigger update_usr_macro_anual_updated_at before update on usr_macro_anual
for each row execute function update_updated_at_column();

-- TABLE: usr_macro_diario
-- DESCRIPCIÓN: Indicadores macroeconómicos diarios (TRM = Tasa Representativa del Mercado, tipo de cambio USD/COP).
-- PROPÓSITO:   Variable exógena si aplica (menos relevante para buñuelos, pero documentada para extensión futura).
-- GRANULARIDAD: Diaria (fecha como date)
-- ACTUALIZACIÓN: Diaria, desde API de Banco de la República o similar
create table public.usr_macro_diario (
  id bigint generated by default as identity not null,
  fecha date not null,
  trm numeric(10, 2) null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  pyme_id text not null default '001_ABC'::text,
  constraint usr_macro_diario_pkey primary key (id)
) tablespace pg_default;

create trigger update_usr_macro_diario_updated_at before update on usr_macro_diario
for each row execute function update_updated_at_column();

-- TABLE: usr_macro_mensual
-- DESCRIPCIÓN: Indicadores macroeconómicos mensuales (inflación anual, desempleo).
-- PROPÓSITO:   Variables exógenas candidatas (CLAUDE.md §7).
-- GRANULARIDAD: Mensual (fecha como date, primer día del mes recomendado)
-- ACTUALIZACIÓN: Mensual, desde fuentes públicas (DANE, etc.)
create table public.usr_macro_mensual (
  id bigint generated by default as identity not null,
  fecha date not null,
  inflacion_anual numeric(5, 2) null,
  desempleo numeric(5, 2) null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  pyme_id text not null default '001_ABC'::text,
  constraint usr_macro_mensual_pkey primary key (id)
) tablespace pg_default;

create trigger update_usr_macro_mensual_updated_at before update on usr_macro_mensual
for each row execute function update_updated_at_column();

-- TABLE: usr_publicidad
-- DESCRIPCIÓN: Inversión y canales de publicidad (Facebook, Instagram, volantes).
-- PROPÓSITO:   Variable exógena candidata. Se espera correlación con demanda durante campañas (CLAUDE.md §8: ciclos promocionales 2x1).
--              Campañas digitales inician 15 días antes de promoción.
-- GRANULARIDAD: Diaria (fecha como date)
-- ACTUALIZACIÓN: Diaria o según campañas activas
create table public.usr_publicidad (
  id bigint generated by default as identity not null,
  fecha date not null,
  campaña text null,
  pauta_facebook numeric(12, 2) null,
  pauta_instagram numeric(12, 2) null,
  volantes_impresos numeric(12, 2) null,
  total_diario numeric(12, 2) null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  pyme_id text not null default '001_ABC'::text,
  constraint usr_publicidad_pkey primary key (id)
) tablespace pg_default;

create trigger update_usr_publicidad_updated_at before update on usr_publicidad
for each row execute function update_updated_at_column();

-- ============================================================
-- 3. CONTROL DE ACCESO (Row Level Security & Credenciales)
-- ============================================================

-- NOTA: RLS (Row Level Security) no está habilitado actualmente.
-- Si se habilita en el futuro, documentar aquí las políticas.

-- ACCESO PÚBLICO (Anon Key de Supabase):
-- ✓ Lectura: usr_ventas, usr_produccion, usr_clima, usr_macro_*
-- ✗ Escritura: Ninguna tabla (prevenir inserciones no autorizadas desde navegador)
-- PROPÓSITO: Dashboard web (read-only para usuarios finales)

-- ACCESO SERVIDOR (Service Role Key):
-- ✓ Lectura completa: Todas las tablas
-- ✓ Escritura completa: Todas las tablas
-- PROPÓSITO: Engine Python (ingesta, transformación, inferencia)

-- CREDENCIALES REQUERIDAS (.env):
-- - SUPABASE_URL: URL del proyecto
-- - SUPABASE_KEY: Anon key (lectura, para Dashboard)
-- - SUPABASE_SERVICE_ROLE_KEY: Service role key (lectura/escritura, para Engine)
-- - SUPABASE_DB: Nombre de la base de datos (cafeteria_sas)

-- ALMACENAMIENTO S3 (DVC / Modelos Entrenados):
-- - SUPABASE_S3_ENDPOINT: URL del bucket
-- - SUPABASE_S3_ACCESS_KEY_ID: Credencial de acceso
-- - SUPABASE_S3_SECRET_ACCESS_KEY: Credencial secreta
-- - SUPABASE_S3_REGION: Región de AWS
-- - SUPABASE_S3_BUCKET: Nombre del bucket
-- PROPÓSITO: Versionamiento de modelos .pkl (no en Git, versionados con DVC)

-- ============================================================
-- CAMBIOS DE VERSIÓN
-- ============================================================
-- v1.0 (2026-03-22): Esquema inicial con 7 tablas. Creado en Etapa 1.2.
